In [ ]:
# welcoming the hero !!!

import numpy as np

## Array

core datatype in numpy , it is a grid of values and it contains information about the raw data.

In [ ]:
arr = np.array([1, 2, 3, 4 , 5])
arr

array([1, 2, 3, 4, 5])

**attributes of array**

In [ ]:
# just looking all of the attributes

[i for i in dir(arr) if not i.startswith("_")]

['T',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

am going through some basic ones

In [ ]:
# checking the shape, which says the size of data

arr.shape

(5,)

In [ ]:
# what about the dimention of the data

arr.ndim

1

In [ ]:
# what about the minimum and maximum val and also the average

print(f"The minimum value - {arr.min()}")
print(f"The maximum value - {arr.max()}")
print(f"The average value - {arr.mean()}")

The minimum value - 1
The maximum value - 5
The average value - 3.0


In [ ]:
# what is the datatype of the arr

arr.dtype

dtype('int64')

Now let's play with the 2d data as well

In [ ]:
ls = [[1,2,3],
    [6,4,2],
    [10,11,12]]

arr = np.array(ls)
arr

array([[ 1,  2,  3],
       [ 6,  4,  2],
       [10, 11, 12]])

in 2d, 0 is for column and 1 for row

In [ ]:
# what is the minimum in column wise

arr.min(axis=0)

array([1, 2, 2])

In [ ]:
# what about the minimum in row wise

arr.min(axis=1)

array([ 1,  2, 10])

In [ ]:
# what is the dimention of the arr

arr.ndim

2

## Creating an array

In [ ]:
# the usual away

arr_sample = np.array([1, 3, 5])
arr_sample

array([1, 3, 5])

In [ ]:
# what if i want an array that contain only zeros ??

zeros = np.zeros(shape=(2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# what if i want an array full of 1s

ones = np.ones((3,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# ah, then I want an array full of my birth year (2005) , he he. what about this

birth_arr = np.full(
    fill_value=2005,
    shape=(4,2),
    dtype=np.int32,   # am just mentioning the dtype also
    )
birth_arr

array([[2005, 2005],
       [2005, 2005],
       [2005, 2005],
       [2005, 2005]], dtype=int32)

In [ ]:
# what if i want a range of numbers

range_arr = np.arange(0, 10, 2)
range_arr

array([0, 2, 4, 6, 8])

In [ ]:
# okay, i want 10 values that between 2 and 7.haha, now you loose little numpy monkey :)

stupid_arr = np.linspace(2, 7, 10)
stupid_arr

array([2.        , 2.55555556, 3.11111111, 3.66666667, 4.22222222,
       4.77777778, 5.33333333, 5.88888889, 6.44444444, 7.        ])

In [ ]:
# now i want an array which contain random values

random_arr = np.random.rand(2, 3)
random_arr

array([[0.77513113, 0.54113051, 0.92842764],
       [0.9786681 , 0.99140165, 0.83654649]])

In [ ]:
# not like that, i want random value within a range.

crazy_random_arr = np.random.randint(10, 50, (4,3)) # bytheway, (4x3 is the shape)
crazy_random_arr

array([[34, 11, 20],
       [46, 18, 15],
       [16, 11, 19],
       [12, 16, 44]])

In [ ]:
# well, now I became a math nerd, give me an identity metrix

identity_thing = np.eye(3)
identity_thing

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# what about the diagonal matrix

diagonal_maaman = np.diag([1,2,3])
diagonal_maaman

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
# hei numpy monkey, give me a meshgrid

x = np.array([1,2])
y = np.array([6,7,9])
meshhh = np.meshgrid(x, y)
meshhh

[array([[1, 2],
        [1, 2],
        [1, 2]]),
 array([[6, 6],
        [7, 7],
        [9, 9]])]

In [ ]:
# checking the shape of meshhh

[i.shape for i in meshhh]

[(3, 2), (3, 2)]

In [ ]:
# a repeated arr by the given shape

base_array = np.array([[1, 2], [3, 4]])
repeated_array = np.tile(base_array, (2, 3))
repeated_array

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [72]:
# an array with nan values

nan_arr = np.array([1,3,4,5,6,np.nan])
nan_arr

array([ 1.,  3.,  4.,  5.,  6., nan])

## Operations on arrays

In [ ]:
# initiating two 1d array

arr1 = np.array([1,2,3])
arr2 = np.array([6,7,8])

In [ ]:
# some arithmatic ones

print(f"Addition        --> {arr1 + arr2}")
print(f"Substraction    --> {arr1 - arr2}")
print(f"Division        --> {arr1 / arr2}")
print(f"Multiplication  --> {arr1 * arr2}")
print(f"Power           --> {arr1 ** arr2}")

Addition        --> [ 7  9 11]
Substraction    --> [-5 -5 -5]
Division        --> [0.16666667 0.28571429 0.375     ]
Multiplication  --> [ 6 14 24]
Power           --> [   1  128 6561]


In [ ]:
# some comparisons

print(f"arr1 values and arr2 values are same      --> {arr1==arr2}")
print(f"arr1 values and arr2 values are not same  --> {arr1!=arr2}")
print(f"arr1 values are greater than arr2 values  --> {arr1>arr2} ")
print(f"arr1 values are less than arr2 values     --> {arr1<arr2}")

arr1 values and arr2 values are same      --> [False False False]
arr1 values and arr2 values are not same  --> [ True  True  True]
arr1 values are greater than arr2 values  --> [False False False] 
arr1 values are less than arr2 values     --> [ True  True  True]


In [ ]:
# some mathematical swimming in arr

print(f"square root of arr1   --> {np.sqrt(arr1)}")
print(f"exponential of arr1   --> {np.exp(arr1)}")
print(f"natural logarithmmmm  --> {np.log(arr1)}")

square root of arr1   --> [1.         1.41421356 1.73205081]
exponential of arr1   --> [ 2.71828183  7.3890561  20.08553692]
natural logarithmmmm  --> [0.         0.69314718 1.09861229]


In [ ]:
# and some trigenomic things also

print(f"sin of arr1   --> {np.sin(arr1)}")
print(f"cos of arr1   --> {np.cos(arr1)}")
print(f"tan of arr1   --> {np.tan(arr1)}")
# cosec, sec ......

sin of arr1   --> [0.84147098 0.90929743 0.14112001]
cos of arr1   --> [ 0.54030231 -0.41614684 -0.9899925 ]
tan of arr1   --> [ 1.55740772 -2.18503986 -0.14254654]


In [ ]:
# some statistical operations also there

print(f"std   --> {np.std(arr1)}")
print(f"variance   --> {np.var(arr1)}")

std   --> 0.816496580927726
variance   --> 0.6666666666666666


In [ ]:
# linear algebra things

print(f"dot product  --> {arr1 @ arr2}")
print(f"matrix multiplication --> {np.matmul(arr1, arr2)}")

dot product  --> 44
matrix multiplication --> 44


## Sorting the Arr

In [77]:
# sorting a 1d array

arr = np.array([7, 12, 4, 6])
arr.sort()
arr

array([ 4,  6,  7, 12])

In [80]:
# sorting a 2d array based on the row

arr = np.array([[1,34,0],
                [6,2,7]])
arr.sort(axis=1)
arr

array([[ 0,  1, 34],
       [ 2,  6,  7]])

In [81]:
# sorting a 2d array based on columns

arr.sort(axis=0)
arr

array([[ 0,  1,  7],
       [ 2,  6, 34]])

In [82]:
# well, what about the argsort, in 1d bytheway

arr = np.array([4,2,7,9,34,74,32,97,1])
arr_indices = arr.argsort()
arr_indices

array([8, 1, 0, 2, 3, 6, 4, 5, 7])

In [83]:
# the use of argsort

arr[arr_indices]

array([ 1,  2,  4,  7,  9, 32, 34, 74, 97])

## Indexing and slicing

## reshaping

## copying

## stacking and splitting

## U func

## Broadcasting

## querying with np