### Getting the libraries

In [10]:
import torch
import numpy as np

### Datatypes

In [2]:
# Tensor

tensor_type = torch.Tensor([1, 2, 3])
print("Tensor:", tensor_type)

Tensor: tensor([1., 2., 3.])


In [3]:
# LongTensor , for integers

long_tensor_type = torch.LongTensor([1, 2, 3])
print("LongTensor:", long_tensor_type)

LongTensor: tensor([1, 2, 3])


In [6]:
# FloatTensor

float_tensor_type = torch.FloatTensor([1, 2, 3])
print("FloatTensor:", float_tensor_type)

FloatTensor: tensor([1., 2., 3.])


In [7]:
# DoubleTensor, specifically for holding double-precision floating-point data.

double_tensor_type = torch.DoubleTensor([1.0, 2.0, 3.0])
print("DoubleTensor:", double_tensor_type)

DoubleTensor: tensor([1., 2., 3.], dtype=torch.float64)


### Creation of tensor

In [14]:
# the simple way, from a list


tensor = torch.tensor([1,3,5], dtype=torch.float)
tensor

tensor([1., 3., 5.])

In [16]:
# from a numpy array

data = np.array([[1,2],
                 [5,6]])
tensor_np = torch.tensor(data)
tensor_np

tensor([[1, 2],
        [5, 6]])

In [18]:
# zeros tensor

zeros_tensor = torch.zeros(3,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
# zeros like another tensor

zeros = torch.zeros_like(tensor_np)
zeros

tensor([[0, 0],
        [0, 0]])

In [22]:
# ones

ones_tensor = torch.ones(4,2)
ones_tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [24]:
# ones like another tensor

ones = torch.ones_like(zeros_tensor)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
# tensor have random value between 0 and 1

rand_tensor = torch.rand(3, 2)
rand_tensor

tensor([[0.6078, 0.7340],
        [0.2340, 0.3786],
        [0.8367, 0.8398]])

In [26]:
# random integers from a uniform distribution

random_tensors = torch.randint(
    low=1,
    high=10,
    size=(3,2),
)
random_tensors

tensor([[6, 5],
        [9, 2],
        [6, 9]])

In [27]:
# tensor with values from 0 to 4

arange_tensor = torch.arange(0, 5)
arange_tensor

tensor([0, 1, 2, 3, 4])

In [28]:
# Tensor with 5 values evenly spaced between 0 and 1

linespace_tensor = torch.linspace( 0, 1, 5)
linespace_tensor

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [30]:
# Identity matrix of size 3x3

identity_matrix = torch.eye(3)
identity_matrixf

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Operations on tensors

In [31]:
# Creating tensors

tensor_a = torch.tensor([1, 2, 3], dtype=torch.float32)
tensor_b = torch.tensor([4, 5, 6], dtype=torch.float32)

In [33]:
# Arithmetic operations

addition_result = tensor_a + tensor_b
addition_result

tensor([5., 7., 9.])

In [34]:
# Arithmetic operations

addition_result = torch.add(tensor_a, tensor_b)
subtraction_result = torch.sub(tensor_a, tensor_b)
multiplication_result = torch.mul(tensor_a, tensor_b)
division_result = torch.div(tensor_a, tensor_b)

In [35]:
print("Tensor A:", tensor_a)
print("Tensor B:", tensor_b)
print("Addition Result:", addition_result)
print("Subtraction Result:", subtraction_result)
print("Multiplication Result:", multiplication_result)
print("Division Result:", division_result)

Tensor A: tensor([1., 2., 3.])
Tensor B: tensor([4., 5., 6.])
Addition Result: tensor([5., 7., 9.])
Subtraction Result: tensor([-3., -3., -3.])
Multiplication Result: tensor([ 4., 10., 18.])
Division Result: tensor([0.2500, 0.4000, 0.5000])


In [36]:
# Element-wise operations

sin_result = torch.sin(tensor_a)
cos_result = torch.cos(tensor_b)
tan_result = torch.tan(tensor_a)

print("Sin Result:", sin_result)
print("Cos Result:", cos_result)
print("Tan Result:", tan_result)

Sin Result: tensor([0.8415, 0.9093, 0.1411])
Cos Result: tensor([-0.6536,  0.2837,  0.9602])
Tan Result: tensor([ 1.5574, -2.1850, -0.1425])


In [39]:
# Reduction operations

sum_result = torch.sum(tensor_a)
mean_result = torch.mean(tensor_b)
max_result, max_index = torch.max(tensor_a, dim=0)
min_result, min_index = torch.min(tensor_b, dim=0)

print("Sum Result:", sum_result)
print("Mean Result:", mean_result)
print("Max Result:", max_result, "at index:", max_index.item())
print("Min Result:", min_result, "at index:", min_index.item())

Sum Result: tensor(6.)
Mean Result: tensor(5.)
Max Result: tensor(3.) at index: tensor(2)
Min Result: tensor(4.) at index: 0


### Indexing and slicing

### Reshaping

### Attributes of tensors

### torch.autograd

### nn module

### Datasets & DataLoaders

### torchvision